apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels: # these labels are deployment labels
    app: mysql
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: mysql
      project: roboshop
      tier: db
  template:
    metadata:
      labels: # these labels are pod labels
        app: mysql
        project: roboshop
        tier: db
    spec:
      serviceAccountName: roboshop-mysql-secret-reader
      volumes:
      - name: secret-volume
        emptyDir: {}
      initContainers:
      - name: fetch-secret
        image: amazon/aws-cli
        command:
        - sh
        - -c
        - >
          aws secretsmanager get-secret-value \
          --region us-east-1 \
          --secret-id roboshop/mysql/password \
          --query SecretString \
          --output text | jq -r .MYSQL_ROOT_PASSWORD > /tmp/mysql/password.txt
        volumeMounts:
        - name: secret-volume
          mountPath: /tmp/mysql
      containers:
      - name: mysql
        image: joindevops/mysql:v1
        imagePullPolicy: Always
        volumeMounts:
        - name: secret-volume
          mountPath: /tmp/mysql
        command: ["sh", "-c"]
        args:
        - |
          export MYSQL_ROOT_PASSWORD=$(cat /tmp/mysql/password.txt)
          exec mysqld
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    app: mysql
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #container-port